const modules=[
  {title:'Introdução ao marketing no automobilismo',xp:80,status:'completed',icon:'01',questions:[]},
  {title:'Patrocínios e negociações',xp:100,status:'completed',icon:'02',questions:[]},
  {title:'Redes sociais e conteúdo',xp:150,status:'current',icon:'03',category:'REDES SOCIAIS E CONTEÚDO',questions:[
    {q:'Qual postagem tem mais potencial de engajamento?',lead:'Escolha a melhor opção para publicar durante o fim de semana de corrida.',scenario:'A piloto terminou o treino livre em P6 e o público está pedindo mais bastidores da equipe.',answers:[['A','Uma arte estática com o resultado do treino','Informação útil, mas com baixo potencial de conversa.'],['B','Vídeo curto de bastidores com a piloto e a equipe','Humaniza a rotina e cria proximidade com quem acompanha o time.'],['C','Repostar apenas a classificação oficial','É informativo, mas pouco proprietário para a marca.']],correct:1,explanation:'Bastidores com pessoas e contexto tendem a gerar mais conexão porque mostram aquilo que o público não vê na transmissão.',tip:'Transforme rotina em narrativa: preparação, tensão e emoção são ativos de conteúdo.',impact:[['Engajamento','+28%'],['Seguidores','+1,8K']]},
    {q:'O que deve aparecer primeiro em um Reels pós-corrida?',lead:'Pense em retenção nos primeiros segundos.',scenario:'A equipe conquistou seu primeiro pódio da temporada e você tem apenas 20 segundos para contar a história.',answers:[['A','Logo da equipe por 4 segundos','Consome o início do vídeo antes da história começar.'],['B','A comemoração do pódio já no primeiro segundo','Entrega emoção imediatamente e aumenta a chance de retenção.'],['C','Tabela completa da corrida','É contexto, mas não é o gancho mais forte.']],correct:1,explanation:'Em vídeo curto, o primeiro segundo precisa entregar o momento de maior tensão ou emoção para segurar a audiência.',tip:'Abra com o clímax e depois explique como a equipe chegou até ele.',impact:[['Retenção','+19%'],['Compartilhamentos','+12%']]},
    {q:'Qual legenda é mais estratégica para um post de bastidores?',lead:'Escolha a opção que combina narrativa e interação.',scenario:'Você tem uma foto da engenheira de performance analisando telemetria antes da classificação.',answers:[['A','“Trabalhando.”','Curta demais e sem contexto.'],['B','“Enquanto o carro está na pista, cada dado conta. Qual detalhe você gostaria de ver no próximo Data Lab?”','Explica o papel técnico e abre conversa com a comunidade.'],['C','“Dia de quali.”','Informa, mas não cria valor adicional.']],correct:1,explanation:'A opção combina educação, bastidores e convite à participação — três elementos úteis para construir comunidade.',tip:'Boas legendas não apenas descrevem a imagem; elas acrescentam contexto ou provocam uma ação.',impact:[['Comentários','+24%'],['Salvamentos','+16%']]},
    {q:'Uma postagem recebe críticas após uma estratégia ruim. O que fazer?',lead:'Pense em confiança e velocidade de resposta.',scenario:'A equipe perdeu posições após uma parada tardia e os comentários estão negativos.',answers:[['A','Apagar todos os comentários críticos','Pode aumentar a percepção de falta de transparência.'],['B','Ignorar até o assunto desaparecer','O silêncio pode deixar outras pessoas definirem a narrativa.'],['C','Reconhecer o resultado, explicar o aprendizado e manter o tom respeitoso','Mostra responsabilidade sem entrar em confronto.']],correct:2,explanation:'Reconhecer o contexto e comunicar aprendizado ajuda a preservar confiança sem alimentar conflito.',tip:'Gestão de comunidade é parte da reputação: responda ao clima, não apenas ao comentário isolado.',impact:[['Reputação','+4'],['Sentimento','+13%']]},
    {q:'Qual conteúdo fecha melhor o fim de semana?',lead:'Escolha o formato que cria continuidade para a próxima etapa.',scenario:'A corrida terminou. Você quer encerrar a narrativa sem deixar o canal “morrer” até a próxima prova.',answers:[['A','Carrossel “5 momentos do nosso fim de semana” + teaser da próxima etapa','Resume a história e cria ponte para o próximo capítulo.'],['B','Apenas uma foto do carro no box','Visualmente boa, mas pouco narrativa.'],['C','Nada até a próxima corrida','Perde o momento em que a atenção ainda está alta.']],correct:0,explanation:'Um fechamento que resume momentos e aponta para a próxima etapa transforma eventos isolados em uma história contínua.',tip:'Pense a temporada como série: cada corrida precisa terminar abrindo o próximo episódio.',impact:[['Fidelização','+17%'],['Alcance','+11%']]}
  ]},
  {title:'Mídia e imprensa',xp:170,status:'locked',icon:'04',questions:[
    {q:'Qual é a melhor estrutura para uma nota após um incidente?',lead:'Escolha uma resposta clara e segura.',scenario:'O carro abandonou após contato. Ainda há informações técnicas sendo verificadas.',answers:[['A','Afirmar imediatamente quem foi culpado','Pode criar conflito antes da confirmação dos fatos.'],['B','Informar o abandono, dizer que a equipe está avaliando os dados e prometer atualização','É transparente sem especular.'],['C','Não publicar nada','Cria vazio informacional.']],correct:1,explanation:'Uma boa nota inicial separa fato confirmado de informação ainda em apuração.',tip:'Velocidade importa, mas precisão protege a reputação.',impact:[['Confiança','+12%'],['Pressão','-8%']]}
  ]},
  {title:'Gestão de crise',xp:190,status:'locked',icon:'05',questions:[
    {q:'Um patrocinador aparece em uma peça com informação errada. Qual é a primeira ação?',lead:'Priorize correção e relacionamento.',scenario:'Um post patrocinado foi ao ar com o nome antigo da campanha da marca.',answers:[['A','Corrigir silenciosamente sem avisar ninguém','Pode funcionar, mas ignora o relacionamento com o parceiro.'],['B','Remover, avisar o patrocinador, corrigir a peça e registrar o aprendizado','Resolve o problema e mantém transparência com o parceiro.'],['C','Culpar o designer publicamente','Escala o problema e prejudica a equipe.']],correct:1,explanation:'Crises pequenas viram grandes quando comunicação e processo falham. Corrigir e alinhar é o caminho mais seguro.',tip:'Em crise, velocidade + responsabilidade + registro de melhoria de processo.',impact:[['Sponsor Score','+1'],['Reputação','+3']]}
  ]},
  {title:'Análise de dados',xp:220,status:'locked',icon:'06',questions:[
    {q:'Qual métrica ajuda mais a comparar conteúdos com alcances muito diferentes?',lead:'Busque uma métrica relativa, não apenas volume bruto.',scenario:'Dois Reels tiveram 20 mil e 80 mil visualizações, mas você quer saber qual gerou mais interação proporcionalmente.',answers:[['A','Número total de curtidas','É volume absoluto.'],['B','Taxa de engajamento','Permite comparar interação em relação à audiência.'],['C','Número de posts no mês','Não mede eficiência do conteúdo.']],correct:1,explanation:'Taxas relativas ajudam a comparar desempenho entre peças com volumes diferentes.',tip:'Nunca leia um número isolado: contexto e denominador mudam a interpretação.',impact:[['Data Skill','+8'],['Decisão','+10%']]}
  ]},
  {title:'Planejamento de campanha',xp:250,status:'locked',icon:'07',boss:true,questions:[
    {q:'Você tem R$ 20 mil para a etapa. Como distribuir melhor?',lead:'Considere objetivo, conteúdo e margem para oportunidade.',scenario:'A meta é crescer comunidade e entregar visibilidade ao patrocinador principal.',answers:[['A','100% em mídia paga antes da corrida','Sem margem para otimização durante o evento.'],['B','Produção + mídia + ativação com patrocinador + reserva de contingência','Equilibra ativos, distribuição e flexibilidade.'],['C','100% em produção audiovisual','Conteúdo sem distribuição pode limitar resultado.']],correct:1,explanation:'Campanhas fortes combinam criação, distribuição, parceria comercial e capacidade de reagir ao que acontece na etapa.',tip:'Planeje o orçamento por função, não por formato.',impact:[['ROI potencial','+21%'],['Sponsor Score','+1']]}
  ]}
];

const races=[['01','BAHRAIN','Sakhir International Circuit','done'],['02','JEDDAH','Jeddah Corniche Circuit','done'],['03','MELBOURNE 🇦🇺','Albert Park Circuit','active'],['04','MIAMI','Miami International Autodrome','locked'],['05','IMOLA','Autodromo Enzo e Dino Ferrari','locked'],['06','MÔNACO','Circuit de Monaco','locked'],['07','BARCELONA','Circuit de Barcelona-Catalunya','locked'],['08','SILVERSTONE','Silverstone Circuit','locked']];
const achievements=[['📣','Primeira campanha','Publique sua primeira ação','unlocked'],['▥','+10K seguidores','Cresça a comunidade','unlocked'],['🤝','Primeiro patrocinador','Feche seu primeiro acordo','unlocked'],['🎬','Especialista em conteúdo','Conclua o Módulo 03','locked'],['🎤','Media Ready','Conclua Mídia e imprensa','locked'],['🛡️','Gestão de crise','Resolva uma crise','locked'],['📊','Data Driven','Conclua Análise de dados','locked'],['🏆','Diretora de Marketing','Finalize a temporada','locked']];

const state={screen:'homeScreen',xp:320,streak:12,lives:5,reputation:78,followers:124000,sponsor:3,currentModule:2,currentQuestion:0,selected:null,correctCount:0,completed:new Set([0,1]),unlocked:new Set([0,1,2])};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen'),navItems=$$('.nav-item[data-screen]'),toast=$('#toast');
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1900)}
function showScreen(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));state.screen=id;navItems.forEach(n=>n.classList.toggle('active',n.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'});}
function hearts(el){el.textContent='♥ '.repeat(state.lives).trim()+' ♡ '.repeat(Math.max(0,5-state.lives)).trim()}
function formatFollowers(n){return n>=1000?`${Math.round(n/1000)}K`:n}
function updateStats(){
  $('#xpTop').textContent=state.xp;$('#xpSeason').textContent=state.xp;$('#streak').textContent=state.streak;$('#streakSeason').textContent=state.streak;$('#livesTop').textContent=state.lives;
  $('#homeRep').textContent=state.reputation;$('#profileRep').textContent=state.reputation;$('#homeFollowers').textContent=formatFollowers(state.followers);$('#profileFollowers').textContent=formatFollowers(state.followers);$('#homeSponsor').textContent=`${state.sponsor}/5`;$('#profileSponsor').textContent=`${state.sponsor}/5`;
  const lvl=state.xp<500?3:state.xp<800?4:5;const floor=lvl===3?0:lvl===4?500:800;const ceil=lvl===3?500:lvl===4?800:1200;const pct=Math.max(0,Math.min(100,((state.xp-floor)/(ceil-floor))*100));
  $('#profileLevel').textContent=`Nível ${lvl}`;$('#levelTitle').textContent=`Nível ${lvl} — ${lvl===3?'Estrategista':lvl===4?'Head de Growth':'Diretora de Marketing'}`;$('#xpProfileText').textContent=`${state.xp} / ${ceil} XP`;$('#xpProfileBar').style.width=`${pct}%`;
  hearts($('#hearts'));hearts($('#resultHearts'));
}
function renderPath(){
  const path=$('#learningPath');path.innerHTML='';
  modules.forEach((m,i)=>{
    const done=state.completed.has(i),unlocked=state.unlocked.has(i),current=i===state.currentModule&&!done;
    const btn=document.createElement('button');btn.className=`lesson ${done?'completed':current?'current':unlocked?'':'locked'} ${m.boss?'boss':''}`;
    const status=done?`Concluído • +${m.xp} XP`:current?`${state.currentQuestion+1} de ${m.questions.length||5} desafios`:unlocked?'Disponível':'Conclua o módulo anterior';
    btn.innerHTML=`<span class="node">${done?'✓':!unlocked?'🔒':m.icon}</span><div><small>MÓDULO ${String(i+1).padStart(2,'0')}</small><strong>${m.title}</strong><span>${status}</span></div><b>›</b>`;
    btn.addEventListener('click',()=>{if(!unlocked)return showToast('Conclua o módulo anterior para desbloquear.');if(done&&m.questions.length===0)return showToast('Módulo concluído.');if(m.questions.length===0)return showToast('Conteúdo demonstrativo já concluído.');startModule(i)});path.appendChild(btn)
  });
  $('#moduleCount').textContent=`${modules.length} módulos`;
}
function startModule(index){state.currentModule=index;state.currentQuestion=0;state.selected=null;state.correctCount=0;renderQuestion();showScreen('quizScreen')}
function renderQuestion(){
  const m=modules[state.currentModule],q=m.questions[state.currentQuestion];if(!q)return;
  $('#quizCategory').textContent=m.category||m.title.toUpperCase();$('#quizNumber').textContent=`${state.currentQuestion+1}.`;$('#quizQuestion').textContent=q.q;$('#quizLead').textContent=q.lead;$('#scenarioText').textContent=q.scenario;
  $('#questionCounter').textContent=`${state.currentQuestion+1}/${m.questions.length}`;$('#quizProgress').style.width=`${((state.currentQuestion+1)/m.questions.length)*100}%`;hearts($('#hearts'));
  const ans=$('#answers');ans.innerHTML='';q.answers.forEach((a,i)=>{const b=document.createElement('button');b.className='answer';b.dataset.index=i;b.innerHTML=`<span class="letter">${a[0]}</span><div><strong>${a[1]}</strong><p>${a[2]}</p></div><i></i>`;b.addEventListener('click',()=>{$$('.answer').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.selected=i;$('#continueQuiz').disabled=false});ans.appendChild(b)});$('#continueQuiz').disabled=true;state.selected=null;
}
function gradeQuestion(){
  const m=modules[state.currentModule],q=m.questions[state.currentQuestion],ok=state.selected===q.correct;
  if(ok){state.correctCount++;state.xp+=30;state.reputation+=1;state.followers+=900;}else{state.lives=Math.max(0,state.lives-1);}
  $('#resultProgress').style.width=`${((state.currentQuestion+1)/m.questions.length)*100}%`;$('#resultCounter').textContent=`${state.currentQuestion+1}/${m.questions.length}`;hearts($('#resultHearts'));
  $('#resultIcon').textContent=ok?'✓':'×';$('#resultIcon').classList.toggle('bad',!ok);$('#resultTitle').textContent=ok?'CORRETO!':'QUASE!';$('#resultTitle').classList.toggle('bad',!ok);$('#resultSubtitle').textContent=ok?'Boa leitura de cenário.':'Veja o raciocínio mais estratégico.';$('#resultExplanation').textContent=q.explanation;$('#resultTip').textContent=q.tip;
  $('#impactGrid').innerHTML=q.impact.map(x=>`<div class="impact-card"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');
  $('#nextQuestion').textContent=state.currentQuestion===m.questions.length-1?'VER RESULTADO':'PRÓXIMA';updateStats();showScreen('resultScreen');
}
function nextQuestion(){const m=modules[state.currentModule];if(state.currentQuestion<m.questions.length-1){state.currentQuestion++;renderQuestion();showScreen('quizScreen')}else completeModule()}
function completeModule(){
  const m=modules[state.currentModule];state.completed.add(state.currentModule);state.unlocked.add(state.currentModule+1);state.xp+=m.xp;state.reputation+=3;if(state.currentModule===2)state.followers+=3200;if(state.currentModule===4)state.sponsor=Math.min(5,state.sponsor+1);
  $('#completeTitle').textContent=m.title;$('#completeCopy').textContent=`Você concluiu ${m.questions.length} desafios e avançou sua carreira.`;$('#completeScore').textContent=`${state.correctCount}/${m.questions.length}`;$('#completeXp').textContent=`+${m.xp + state.correctCount*30}`;$('#completeRep').textContent='+3';updateStats();renderPath();renderAchievements();showScreen('moduleCompleteScreen')
}
function renderSeason(){const list=$('#seasonList');list.innerHTML=races.map(r=>`<div class="race ${r[3]==='done'?'done':r[3]==='active'?'active-race':''}"><span class="race-no">${r[0]}</span><span class="track"></span><div><strong>${r[1]}</strong><small>${r[2]}</small></div><b>${r[3]==='done'?'✓':r[3]==='active'?'AGORA':'🔒'}</b></div>`).join('')}
function renderAchievements(){
  if(state.completed.has(2))achievements[3][3]='unlocked';if(state.completed.has(3))achievements[4][3]='unlocked';if(state.completed.has(4))achievements[5][3]='unlocked';if(state.completed.has(5))achievements[6][3]='unlocked';
  const unlocked=achievements.filter(a=>a[3]==='unlocked').length;$('#achievementCount').textContent=`${unlocked}/${achievements.length}`;$('#achievementsGrid').innerHTML=achievements.map(a=>`<div class="achievement ${a[3]==='unlocked'?'unlocked':''}"><span>${a[0]}</span><strong>${a[1]}</strong><small>${a[2]}</small></div>`).join('')
}
function runDaily(){const prompts=['A equipe ganhou 2 mil seguidores após um pódio. Qual é a melhor próxima ação?','Um patrocinador marcou a equipe em um post. Como aproveitar o momento?','Seu Reels teve alcance alto e poucos comentários. O que testar agora?'];const p=prompts[Math.floor(Date.now()/86400000)%prompts.length];showToast(`Briefing: ${p}`);state.xp+=20;state.streak+=1;updateStats()}

$$('[data-screen]').forEach(btn=>btn.addEventListener('click',()=>{showScreen(btn.dataset.screen);closeDrawer()}));$$('[data-back]').forEach(btn=>btn.addEventListener('click',()=>showScreen('homeScreen')));$('#missionBtn').addEventListener('click',()=>startModule(2));$('#dailyBtn').addEventListener('click',runDaily);$('#continueQuiz').addEventListener('click',gradeQuestion);$('#nextQuestion').addEventListener('click',nextQuestion);$('#finishModuleBtn').addEventListener('click',()=>showScreen('homeScreen'));$('#profileBtn').addEventListener('click',()=>showScreen('profileScreen'));
const drawer=$('#drawer'),scrim=$('#scrim');function openDrawer(){drawer.classList.add('open');scrim.classList.add('show');drawer.setAttribute('aria-hidden','false')}function closeDrawer(){drawer.classList.remove('open');scrim.classList.remove('show');drawer.setAttribute('aria-hidden','true')}$('#menuBtn').addEventListener('click',openDrawer);$('#closeDrawer').addEventListener('click',closeDrawer);scrim.addEventListener('click',closeDrawer);
$('#resetBtn').addEventListener('click',()=>{state.xp=320;state.streak=12;state.lives=5;state.reputation=78;state.followers=124000;state.sponsor=3;state.currentModule=2;state.currentQuestion=0;state.selected=null;state.correctCount=0;state.completed=new Set([0,1]);state.unlocked=new Set([0,1,2]);modules.forEach((m,i)=>m.status=i<2?'completed':i===2?'current':'locked');renderAll();showScreen('homeScreen');showToast('Demonstração reiniciada.');closeDrawer()});
function renderAll(){renderPath();renderSeason();renderAchievements();updateStats()}
renderAll();
