const modules=[
  {title:'Introdução ao marketing no automobilismo',icon:'campaign',xp:80,questions:[],category:'INTRODUÇÃO'},
  {title:'Patrocínios e negociações',icon:'handshake',xp:100,questions:[],category:'PATROCÍNIOS'},
  {title:'Redes sociais e conteúdo',icon:'bar_chart',xp:150,category:'REDES SOCIAIS E CONTEÚDO',questions:[
    {q:'Qual postagem tem mais potencial de engajamento?',lead:'Escolha a opção mais estratégica para publicar durante o fim de semana de corrida.',scenario:'A equipe saiu do treino livre em P3. O público está curioso sobre o clima interno da equipe e o desempenho da pilota.',answers:[['A','Bastidores do treino livre','Vídeo curto mostrando rotina e emoção no box'],['B','Entrevista exclusiva com a pilota','Conteúdo direto e institucional'],['C','Resultado completo do treino','Post puramente informativo']],correct:0,explanation:'Conteúdos de bastidores aproximam o público, humanizam a equipe e geram mais compartilhamentos ao longo do fim de semana.',tip:'Antes de pensar apenas no resultado, mostre as pessoas, o processo e a atmosfera da equipe.',impact:[['Engajamento estimado','+28%'],['Afinidade com a marca','Alta'],['Crescimento de seguidores','+900'] ]},
    {q:'O patrocinador quer aparecer mais. Qual formato faz mais sentido?',lead:'Escolha a opção que entrega visibilidade sem prejudicar a experiência do público.',scenario:'Uma marca parceira pediu maior presença durante a classificação, mas a comunidade costuma rejeitar posts muito publicitários.',answers:[['A','Post promocional com preço e CTA agressivo','Foco total na oferta'],['B','Conteúdo de bastidor integrado à marca','Mostra produto ou ação dentro do contexto da equipe'],['C','Trocar a foto de perfil pelo logo do patrocinador','Alta visibilidade imediata']],correct:1,explanation:'A integração natural no contexto da equipe aumenta lembrança de marca sem parecer invasiva.',tip:'Patrocínio performa melhor quando aparece como parte da história, não como interrupção.',impact:[['Memória de marca','+18%'],['Rejeição do público','Baixa'],['Valor para sponsor','Mais forte']]},
    {q:'A equipe teve um bom quali. Qual deve ser a ordem do conteúdo?',lead:'Pense em narrativa e retenção ao longo das horas seguintes.',scenario:'A equipe conseguiu um top 5 inesperado. Você precisa sustentar o interesse da audiência até a corrida.',answers:[['A','Publicar tudo de uma vez','Resultado, fala da pilota e bastidores ao mesmo tempo'],['B','Soltar apenas a arte oficial da classificação','Comunicação segura e simples'],['C','Arte do resultado, reação rápida e depois bastidores','Cria continuidade narrativa']],correct:2,explanation:'Distribuir o conteúdo em ondas cria retenção, aumenta tempo de atenção e multiplica pontos de contato com o público.',tip:'Boas coberturas funcionam como sequência, não como postagem isolada.',impact:[['Retenção','Maior'],['Tempo de atenção','+22%'],['Volume de conteúdo útil','Equilibrado']]},
    {q:'Um Reels performou bem, mas os comentários foram baixos. O que fazer?',lead:'Escolha a alternativa com melhor leitura de métrica.',scenario:'O alcance foi ótimo, mas pouca gente comentou. A equipe quer aumentar interação mais profunda.',answers:[['A','Repetir o mesmo formato exatamente igual','Se deu alcance, vai funcionar de novo'],['B','Criar uma continuação com pergunta clara para a comunidade','Usar o bom alcance para puxar conversa'],['C','Parar de investir em vídeo e voltar para carrossel','Mudar tudo rapidamente']],correct:1,explanation:'Quando o alcance já está bom, o ajuste ideal é trabalhar interação e não abandonar o formato de melhor distribuição.',tip:'Use a próxima peça para converter alcance em conversa.',impact:[['Comentários','+35%'],['Alcance','Mantido'],['Comunidade','Mais ativa']]},
    {q:'Qual KPI melhor indica conexão com a comunidade?',lead:'Nem sempre o maior número é o mais importante.',scenario:'Você precisa apresentar ao chefe da equipe um indicador que mostre relação real entre conteúdo e fãs.',answers:[['A','Impressões totais','Mostra exposição geral'],['B','Curtidas somadas','Número fácil de comunicar'],['C','Taxa de engajamento e respostas qualitativas','Mostra profundidade e relevância']],correct:2,explanation:'Para medir conexão, taxa de engajamento somada a sinais qualitativos oferece visão muito melhor do relacionamento com a audiência.',tip:'Métricas de vaidade não contam a história completa.',impact:[['Leitura estratégica','Mais precisa'],['Aprendizado','Maior'],['Tomada de decisão','Melhor']]}
  ]},
  {title:'Mídia e imprensa',icon:'mic_external_on',xp:120,questions:[],category:'IMPRENSA'},
  {title:'Gestão de crise',icon:'shield',xp:140,questions:[],category:'CRISE'},
  {title:'Análise de dados',icon:'query_stats',xp:130,questions:[],category:'DADOS'},
  {title:'Planejamento de campanha',icon:'chess',xp:160,questions:[],category:'CAMPANHAS'}
];
const races=[['01','BAHRAIN','Sakhir International Circuit','done'],['02','JEDDAH','Jeddah Corniche Circuit','done'],['03','MELBOURNE','Albert Park Circuit','active'],['04','MIAMI','Miami International Autodrome','locked'],['05','IMOLA','Autodromo Enzo e Dino Ferrari','locked'],['06','MÔNACO','Circuit de Monaco','locked'],['07','BARCELONA','Circuit de Barcelona-Catalunya','locked'],['08','SILVERSTONE','Silverstone Circuit','locked']];
const achievements=[['campaign','Primeira campanha','Publique sua primeira ação','unlocked'],['groups','+10K seguidores','Cresça a comunidade','unlocked'],['handshake','Primeiro patrocinador','Feche seu primeiro acordo','unlocked'],['movie','Especialista em conteúdo','Conclua o Módulo 03','locked'],['mic_external_on','Media Ready','Conclua Mídia e imprensa','locked'],['shield','Gestão de crise','Resolva uma crise','locked'],['query_stats','Data Driven','Conclua Análise de dados','locked'],['emoji_events','Diretora de Marketing','Finalize a temporada','locked']];

const dailyQuestions=[
  {q:'A equipe ganhou 2 mil seguidores após um pódio. Qual é a melhor próxima ação?',lead:'Aproveite o pico de atenção sem desperdiçar o momento.',scenario:'O pódio aconteceu há poucas horas e o perfil está recebendo muito mais visitas que o normal.',answers:[['A','Esperar a próxima corrida para postar algo novo','Deixa o pico de atenção esfriar sem aproveitar'],['B','Publicar bastidores do pódio e convidar os novos seguidores a conhecer a equipe','Usa o momento de pico para converter visitantes em comunidade'],['C','Trocar a foto de perfil e não postar mais nada','Pouco conteúdo pra sustentar o interesse']],correct:1,explanation:'Picos de atenção são janelas curtas: o ideal é publicar logo e convidar quem chegou agora a continuar acompanhando.',tip:'Aproveite o momento quente — audiência nova precisa de um motivo pra ficar.',impact:[['Novos seguidores retidos','+40%'],['Engajamento no pico','Alto']]},
  {q:'Um patrocinador marcou a equipe em um post. Como aproveitar o momento?',lead:'Pense em relacionamento, não só em visibilidade.',scenario:'A marca parceira publicou algo espontâneo marcando a equipe, sem ter sido combinado antes.',answers:[['A','Ignorar, já que não foi planejado pela equipe','Perde a chance de fortalecer a parceria'],['B','Reagir rápido, compartilhar e agradecer publicamente','Fortalece o relacionamento e amplia o alcance do post'],['C','Pedir pra marca apagar e fazer um post mais formal depois','Desperdiça a espontaneidade, que costuma performar melhor']],correct:1,explanation:'Reagir rápido e publicamente a uma menção espontânea do patrocinador reforça a parceria e aproveita o alcance orgânico dela.',tip:'Menções espontâneas de parceiros valem mais quando respondidas na hora.',impact:[['Valor percebido pelo sponsor','Maior'],['Alcance combinado','+15%']]},
  {q:'Seu Reels teve alcance alto e poucos comentários. O que testar agora?',lead:'O alcance já está bom — o próximo passo é gerar conversa.',scenario:'O vídeo circulou bastante, mas quase ninguém comentou ou fez perguntas.',answers:[['A','Postar o mesmo vídeo de novo em outro horário','Não resolve a falta de interação'],['B','Fazer uma continuação com uma pergunta direta pra audiência responder','Transforma alcance em conversa real'],['C','Parar de fazer Reels e voltar só pra posts estáticos','Abandona o formato que já está performando bem em alcance']],correct:1,explanation:'Quando o alcance já é bom, o próximo passo é puxar interação com uma pergunta clara, não abandonar o formato.',tip:'Alcance alto + pergunta direta costuma ser a combinação que gera mais comentários.',impact:[['Comentários esperados','+30%'],['Alcance','Mantido']]}
];
const state={screen:'homeScreen',xp:320,streak:12,reputation:78,followers:124000,sponsor:3,currentModule:2,currentQuestion:0,selected:null,correctCount:0,completed:new Set([0,1]),unlocked:new Set([0,1,2]),dailyMode:false};
let currentDaily=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen'),navItems=$$('.nav-item[data-screen]'),toast=$('#toast');
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1900)}
function showScreen(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));state.screen=id;navItems.forEach(n=>n.classList.toggle('active',n.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'});}
function formatFollowers(n){return n>=1000?`${Math.round(n/1000)}K`:n}
function updateStats(){
  $('#xpTop').textContent=state.xp;$('#xpSeason').textContent=state.xp;$('#streak').textContent=state.streak;$('#streakSeason').textContent=state.streak;
  $('#homeRep').textContent=state.reputation;$('#profileRep').textContent=state.reputation;$('#homeFollowers').textContent=formatFollowers(state.followers);$('#profileFollowers').textContent=formatFollowers(state.followers);$('#homeSponsor').textContent=`${state.sponsor}/5`;$('#profileSponsor').textContent=`${state.sponsor}/5`;
  const lvl=state.xp<500?3:state.xp<800?4:5;const floor=lvl===3?0:lvl===4?500:800;const ceil=lvl===3?500:lvl===4?800:1200;const pct=Math.max(0,Math.min(100,((state.xp-floor)/(ceil-floor))*100));
  $('#profileLevel').textContent=`Nível ${lvl}`;$('#levelTitle').textContent=`Nível ${lvl} — ${lvl===3?'Estrategista':lvl===4?'Head de Growth':'Diretora de Marketing'}`;$('#xpProfileText').textContent=`${state.xp} / ${ceil} XP`;$('#xpProfileBar').style.width=`${pct}%`;
}
function renderPath(){
  const path=$('#learningPath');path.innerHTML='';
  modules.forEach((m,i)=>{
    const done=state.completed.has(i),unlocked=state.unlocked.has(i),current=i===state.currentModule&&!done;
    const btn=document.createElement('button');btn.className=`lesson ${done?'completed':current?'current':unlocked?'':'locked'} ${m.boss?'boss':''}`;
    const status=done?`Concluído • +${m.xp} XP`:current?`${state.currentQuestion+1} de ${m.questions.length||5} desafios`:unlocked?'Disponível':'Conclua o módulo anterior';
    const iconHtml=done?'<span class="msym">check</span>':!unlocked?'<span class="msym">lock</span>':`<span class="msym">${m.icon}</span>`;
    btn.innerHTML=`<span class="node">${iconHtml}</span><div><small>MÓDULO ${String(i+1).padStart(2,'0')}</small><strong>${m.title}</strong><span>${status}</span></div><b>›</b>`;
    btn.addEventListener('click',()=>{if(!unlocked)return showToast('Conclua o módulo anterior para desbloquear.');if(done&&m.questions.length===0)return showToast('Módulo concluído.');if(m.questions.length===0)return showToast('Conteúdo demonstrativo já concluído.');startModule(i)});path.appendChild(btn)
  });
  $('#moduleCount').textContent=`${modules.length} módulos`;
}
function startModule(index){state.dailyMode=false;state.currentModule=index;state.currentQuestion=0;state.selected=null;state.correctCount=0;renderQuestion();showScreen('quizScreen')}
function startDaily(){
  state.dailyMode=true;state.selected=null;
  currentDaily=dailyQuestions[Math.floor(Date.now()/86400000)%dailyQuestions.length];
  renderQuestion();showScreen('quizScreen');
}
function renderQuestion(){
  const q=state.dailyMode?currentDaily:modules[state.currentModule].questions[state.currentQuestion];if(!q)return;
  const m=state.dailyMode?null:modules[state.currentModule];
  $('#quizCategory').textContent=state.dailyMode?'DESAFIO RÁPIDO':(m.category||m.title.toUpperCase());$('#quizNumber').textContent=state.dailyMode?'':'1.';$('#quizQuestion').textContent=q.q;$('#quizLead').textContent=q.lead;$('#scenarioText').textContent=q.scenario;
  $('#questionCounter').textContent=state.dailyMode?'1/1':`${state.currentQuestion+1}/${m.questions.length}`;$('#quizProgress').style.width=state.dailyMode?'100%':`${((state.currentQuestion+1)/m.questions.length)*100}%`;
  const ans=$('#answers');ans.innerHTML='';q.answers.forEach((a,i)=>{const b=document.createElement('button');b.className='answer';b.dataset.index=i;b.innerHTML=`<span class="letter">${a[0]}</span><div><strong>${a[1]}</strong><p>${a[2]}</p></div><i></i>`;b.addEventListener('click',()=>{$$('.answer').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.selected=i;$('#continueQuiz').disabled=false});ans.appendChild(b)});$('#continueQuiz').disabled=true;state.selected=null;
}
function gradeQuestion(){
  const q=state.dailyMode?currentDaily:modules[state.currentModule].questions[state.currentQuestion];
  const m=state.dailyMode?null:modules[state.currentModule];
  const ok=state.selected===q.correct;
  if(ok){state.correctCount++;state.xp+=state.dailyMode?20:30;state.reputation+=1;state.followers+=900;if(state.dailyMode)state.streak+=1;}
  $('#resultProgress').style.width=state.dailyMode?'100%':`${((state.currentQuestion+1)/m.questions.length)*100}%`;$('#resultCounter').textContent=state.dailyMode?'1/1':`${state.currentQuestion+1}/${m.questions.length}`;
  $('#resultIcon').textContent=ok?'✓':'×';$('#resultIcon').classList.toggle('bad',!ok);$('#resultTitle').textContent=ok?'CORRETO!':'QUASE!';$('#resultTitle').classList.toggle('bad',!ok);$('#resultSubtitle').textContent=ok?'Boa leitura de cenário.':'Veja o raciocínio mais estratégico.';$('#resultExplanation').textContent=q.explanation;$('#resultTip').textContent=q.tip;
  $('#impactGrid').innerHTML=q.impact.map(x=>`<div class="impact-card"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');
  $('#nextQuestion').textContent=state.dailyMode?'CONCLUIR':(state.currentQuestion===m.questions.length-1?'VER RESULTADO':'PRÓXIMA');updateStats();showScreen('resultScreen');
}
function nextQuestion(){
  if(state.dailyMode){state.dailyMode=false;currentDaily=null;updateStats();showScreen('homeScreen');showToast('Desafio rápido concluído • +20 XP');return}
  const m=modules[state.currentModule];if(state.currentQuestion<m.questions.length-1){state.currentQuestion++;renderQuestion();showScreen('quizScreen')}else completeModule()
}
function completeModule(){
  const m=modules[state.currentModule];state.completed.add(state.currentModule);state.unlocked.add(state.currentModule+1);state.xp+=m.xp;state.reputation+=3;if(state.currentModule===2)state.followers+=3200;if(state.currentModule===4)state.sponsor=Math.min(5,state.sponsor+1);
  $('#completeTitle').textContent=m.title;$('#completeCopy').textContent=`Você concluiu ${m.questions.length} desafios e avançou sua carreira.`;$('#completeScore').textContent=`${state.correctCount}/${m.questions.length}`;$('#completeXp').textContent=`+${m.xp + state.correctCount*30}`;$('#completeRep').textContent='+3';updateStats();renderPath();renderAchievements();showScreen('moduleCompleteScreen')
}
function renderSeason(){const list=$('#seasonList');list.innerHTML=races.map(r=>`<div class="race ${r[3]==='done'?'done':r[3]==='active'?'active-race':''}"><span class="race-no">${r[0]}</span><span class="track"></span><div><strong>${r[1]}</strong><small>${r[2]}</small></div><b>${r[3]==='done'?'✓':r[3]==='active'?'AGORA':'🔒'}</b></div>`).join('')}
function renderAchievements(){
  if(state.completed.has(2))achievements[3][3]='unlocked';if(state.completed.has(3))achievements[4][3]='unlocked';if(state.completed.has(4))achievements[5][3]='unlocked';if(state.completed.has(5))achievements[6][3]='unlocked';
  const unlocked=achievements.filter(a=>a[3]==='unlocked').length;$('#achievementCount').textContent=`${unlocked}/${achievements.length}`;$('#achievementsGrid').innerHTML=achievements.map(a=>`<div class="achievement ${a[3]==='unlocked'?'unlocked':''}"><span class="msym">${a[0]}</span><strong>${a[1]}</strong><small>${a[2]}</small></div>`).join('')
}
$$('[data-screen]').forEach(btn=>btn.addEventListener('click',()=>{showScreen(btn.dataset.screen);closeDrawer()}));$$('[data-back]').forEach(btn=>btn.addEventListener('click',()=>{state.dailyMode=false;showScreen('homeScreen')}));$('#missionBtn').addEventListener('click',()=>startModule(2));$('#dailyBtn').addEventListener('click',startDaily);$('#continueQuiz').addEventListener('click',gradeQuestion);$('#nextQuestion').addEventListener('click',nextQuestion);$('#finishModuleBtn').addEventListener('click',()=>showScreen('homeScreen'));$('#profileBtn').addEventListener('click',()=>showScreen('profileScreen'));
const drawer=$('#drawer'),scrim=$('#scrim');function openDrawer(){if(window.innerWidth>=980)return;drawer.classList.add('open');scrim.classList.add('show');drawer.setAttribute('aria-hidden','false')}function closeDrawer(){drawer.classList.remove('open');scrim.classList.remove('show');drawer.setAttribute('aria-hidden','true')}$('#menuBtn').addEventListener('click',openDrawer);$('#closeDrawer').addEventListener('click',closeDrawer);scrim.addEventListener('click',closeDrawer);
$('#resetBtn').addEventListener('click',()=>{state.xp=320;state.streak=12;state.reputation=78;state.followers=124000;state.sponsor=3;state.currentModule=2;state.currentQuestion=0;state.selected=null;state.correctCount=0;state.completed=new Set([0,1]);state.unlocked=new Set([0,1,2]);renderAll();showScreen('homeScreen');showToast('Demonstração reiniciada.');closeDrawer()});
function renderAll(){renderPath();renderSeason();renderAchievements();updateStats()}
renderAll();
